apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
    app: frontend
spec:
  containers:
  - name: nginx-container
    image: nginx
    ports:
    - containerPort: 80

  nodeName: cka-cluster2-worker2  #it will schedule the pod on worker2 node, this is called manual scheduling, if you want to schedule the pod you need to use nodeSelector or affinity, but this is not recommended in production environment.
