apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    tier: backend
spec:
  replicas: 3
  template:
    metadata:
      name: nginx-pod
      labels:
        app: v1
    spec:
      containers:
      - name: nginx
        image: nginx:1.23.0
        ports:
        - containerPort: 80
  selector:
    matchLabels:
      app: v1

#List the Deployment and ensure the correct number of replicas is running. (kubectl get deployments)
#Update the image to nginx:1.23.4. (kubectl set image deployment/nginx nginx=nginx:1.23.4)
#kubectl describe deployment nginx
#kubectl rollout status deployment/nginx ( verification command )
# Assign the change cause "Pick up patch version" to the revision. cmd --->kubectl annotate deployment nginx kubernetes.io/change-cause="Pick up patch version"
#Scale the Deployment to 5 replicas. ( kubectl scale deployment nginx --replicas=5)
#Revert the Deployment to revision 1. kubectl rollout undo deployment nginx --to revision=1
# revision =1 due to history of deployment, if you want to check the history of deployment use this command ---> kubectl rollout history deployment nginx
#now check the image version of the pod using this command ---> kubectl describe pod <pod name> | grep Image


#Note: 
#1.kubectl set image deployment deployment-name container-name=image:tag is used to update the image of the deployment. it will create a new revision of the deployment and rollout the new image to the pods.
#2.annotate is to add metadata to deployment. we can add also in metadata section of deployment.yml file. but if we want to add it after deployment is created then we can use annotate command.
#3. kubectl annotate deployment nginx kubernetes.io/change-cause="Pick up patch version"  this command is used to add metadata to the deployment after it is created. we can also add it in the metadata section of the deployment.yml file. but if we want to add it after deployment is created then we can use annotate command.
#4.kubectl rollout history deployment <deployment name> this command is used to check the history of the deployment. it will show the revision number and the change cause.
#5.so in revision 1 the image is nginx:1.23.0 and in revision 2 the image is nginx:1.23.4. so when we rollback to revision 1 the image will be reverted to nginx:1.23.0.
#6. kubectl rollout undo deployment <deployment name> --to revision=<revision number> this command is used to rollback the deployment to a specific revision. it will revert the deployment to the state it was in at that revision.
#7.kubectl get rs this command is used to get the replica sets of the deployment. it will show the replica sets created by the deployment and their status.