apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: node-affinity-pod
  name: node-affinity-pod
spec:
  containers:
  - image: nginx
    name: node-affinity-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: disktype
            operator: In
            values:
            - ssd
status: {}
