apiVersion: v1
kind: Pod
metadata:
  name: multicontainer
spec:
  containers:
  - name: nginx
    image: nginx

  - name: busybox
    image: busybox
    command:
    - sh
    - -c
    - |
      while true
      do
        wget -qO- http://localhost
        sleep 10
      done


#command: ["sh", "-c", "while true; do wget -qO- http://localhost; sleep 10; done"] ----> we can give in single line.


#BusyBox is a lightweight Linux container. In my multi-container Pod, I'm using it as a second container to run a continuous command,
#demonstrating that multiple containers can run together inside the same Pod."

#-qO - Quietly send an HTTP request to port 80 on localhost and print the response directly to the terminal.

#kubectl apply -f multipodcontainer.yml
#kubectl get pods multicontainer
#kubectl describe pod multicontainer

# kubectl logs multicontainer -c busybox ----> to watch the logs of busybox container in multicontainer pod 

# kubectl logs -f multicontainer -c busybox ----> to watch the logs of busybox container in multicontainer pod in real time.
#( it will continuously get the response from nginx container running in the same pod and print it to the terminal every 10 seconds. )